sonar.projectKey=AGES-RFID_backend
sonar.organization=ages-rfid

sonar.sources=Backend.API
sonar.tests=Backend.Tests.Integration, Backend.Tests.Unit

sonar.exclusions=Backend.API/Database/Migrations/**
