// <auto-generated />
using System;
using Backend.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260408214415_AddVehiclesTagsAndAccesses")]
    partial class AddVehiclesTagsAndAccesses
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Features.Accesses.Access", b =>
                {
                    b.Property<Guid>("AccessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("access_id");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamptz")
                        .HasColumnName("timestamp");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.HasKey("AccessId")
                        .HasName("pk_accesses");

                    b.HasIndex("TagId")
                        .HasDatabaseName("ix_accesses_tag_id");

                    b.ToTable("accesses", (string)null);
                });

            modelBuilder.Entity("Backend.Features.Tags.Tag", b =>
                {
                    b.Property<Guid>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid?>("VeichleId")
                        .HasColumnType("uuid")
                        .HasColumnName("veichle_id");

                    b.HasKey("TagId")
                        .HasName("pk_tags");

                    b.HasIndex("VeichleId")
                        .IsUnique()
                        .HasDatabaseName("ix_tags_veichle_id")
                        .HasFilter("status = 'InUse'");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("Backend.Features.Users.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar")
                        .HasColumnName("cpf");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar")
                        .HasColumnName("phone_number");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("UserId")
                        .HasName("pk_users");

                    b.HasIndex("Cpf")
                        .IsUnique()
                        .HasDatabaseName("ix_users_cpf");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_users_phone_number");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Backend.Features.Vehicles.Vehicle", b =>
                {
                    b.Property<Guid>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("brand");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("color");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("model");

                    b.Property<string>("Plate")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("plate");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("VehicleId")
                        .HasName("pk_vehicles");

                    b.HasIndex("Plate")
                        .IsUnique()
                        .HasDatabaseName("ix_vehicles_plate");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_vehicles_user_id");

                    b.ToTable("vehicles", (string)null);
                });

            modelBuilder.Entity("Backend.Features.Accesses.Access", b =>
                {
                    b.HasOne("Backend.Features.Tags.Tag", "Tag")
                        .WithMany("Accesses")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_accesses_tags_tag_id");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Backend.Features.Tags.Tag", b =>
                {
                    b.HasOne("Backend.Features.Vehicles.Vehicle", "Veichle")
                        .WithMany("Tags")
                        .HasForeignKey("VeichleId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_tags_vehicles_veichle_id");

                    b.Navigation("Veichle");
                });

            modelBuilder.Entity("Backend.Features.Vehicles.Vehicle", b =>
                {
                    b.HasOne("Backend.Features.Users.User", "User")
                        .WithMany("Vehicles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vehicles_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Features.Tags.Tag", b =>
                {
                    b.Navigation("Accesses");
                });

            modelBuilder.Entity("Backend.Features.Users.User", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("Backend.Features.Vehicles.Vehicle", b =>
                {
                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
