// <auto-generated />
using System;
using Backend.Database;
using Backend.Features.Accesses;
using Backend.Features.Transactions;
using Backend.Features.Users;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "access_type", new[] { "exit", "entry" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "transaction_type", new[] { "deposit", "withdrawal" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "user_role", new[] { "admin", "customer" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Features.Accesses.Access", b =>
                {
                    b.Property<Guid>("AccessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("access_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp")
                        .HasDefaultValueSql("now()");

                    b.Property<AccessType>("Type")
                        .HasColumnType("access_type")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("AccessId")
                        .HasName("pk_accesses");

                    b.HasIndex("TagId")
                        .HasDatabaseName("ix_accesses_tag_id");

                    b.ToTable("accesses", (string)null);
                });

            modelBuilder.Entity("Backend.Features.ParkingPrices.ParkingPrice", b =>
                {
                    b.Property<Guid>("ParkingPriceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("parking_price_id");

                    b.Property<decimal>("BasePrice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(14,2)")
                        .HasDefaultValue(15.00m)
                        .HasColumnName("base_price");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("HourlyRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(14,2)")
                        .HasDefaultValue(5.00m)
                        .HasColumnName("hourly_rate");

                    b.Property<int>("ThresholdMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(180)
                        .HasColumnName("threshold_minutes");

                    b.Property<int>("ToleranceMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(15)
                        .HasColumnName("tolerance_minutes");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("ParkingPriceId")
                        .HasName("pk_parking_prices");

                    b.ToTable("parking_prices", (string)null);
                });

            modelBuilder.Entity("Backend.Features.GatewayStatus.ReaderStatus", b =>
                {
                    b.Property<Guid>("ReaderId")
                        .HasColumnType("uuid")
                        .HasColumnName("reader_id");

                    b.Property<DateTime>("LastPing")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_ping");

                    b.Property<string>("ReaderStatusValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reader_status");

                    b.HasKey("ReaderId")
                        .HasName("pk_reader_status");

                    b.ToTable("reader_status", (string)null);
                });
                
            modelBuilder.Entity("Backend.Features.Settings.Settings", b =>
                {
                    b.Property<Guid>("SettingsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("settings_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("SettingsId")
                        .HasName("pk_settings");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_settings_name");

                    b.ToTable("settings", (string)null);
                });

            modelBuilder.Entity("Backend.Features.Tags.Tag", b =>
                {
                    b.Property<Guid>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Epc")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("epc");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("status");

                    b.Property<string>("Tid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tid");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("TagId")
                        .HasName("pk_tags");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("Backend.Features.Transactions.Transaction", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("transaction_id");

                    b.Property<Guid?>("AccessId")
                        .HasColumnType("uuid")
                        .HasColumnName("access_id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<TransactionType>("TransactionType")
                        .HasColumnType("transaction_type")
                        .HasColumnName("transaction_type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("TransactionId")
                        .HasName("pk_transactions");

                    b.HasIndex("AccessId")
                        .HasDatabaseName("ix_transactions_access_id");

                    b.ToTable("transactions", (string)null);
                });

            modelBuilder.Entity("Backend.Features.Users.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Cellphone")
                        .HasColumnType("text")
                        .HasColumnName("cellphone");

                    b.Property<string>("Cpf")
                        .HasColumnType("text")
                        .HasColumnName("cpf");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<UserRole>("Role")
                        .HasColumnType("user_role")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("UserId")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Backend.Features.Vehicles.Vehicle", b =>
                {
                    b.Property<Guid>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("brand");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model");

                    b.Property<string>("Plate")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("plate");

                    b.Property<Guid?>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("VehicleId")
                        .HasName("pk_vehicles");

                    b.HasIndex("Plate")
                        .IsUnique()
                        .HasDatabaseName("ix_vehicles_plate");

                    b.HasIndex("TagId")
                        .IsUnique()
                        .HasDatabaseName("ix_vehicles_tag_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_vehicles_user_id");

                    b.ToTable("vehicles", (string)null);
                });

            modelBuilder.Entity("Backend.Features.GatewayStatus.ReaderStatus", b =>
                {
                    b.OwnsMany("Backend.Features.GatewayStatus.ReaderAntennaStatus", "AntennaList", b1 =>
                        {
                            b1.Property<Guid>("ReaderStatusReaderId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<string>("AntennaStatus")
                                .IsRequired()
                                .HasJsonPropertyName("antenna_status")
                                .HasColumnType("text");

                            b1.Property<int>("Port")
                                .HasJsonPropertyName("port")
                                .HasColumnType("integer");

                            b1.Property<double>("Power")
                                .HasJsonPropertyName("power")
                                .HasColumnType("double precision");

                            b1.Property<double>("Sensitivity")
                                .HasJsonPropertyName("sensitivity")
                                .HasColumnType("double precision");

                            b1.HasKey("ReaderStatusReaderId", "Id");

                            b1.ToJson("antenna_list");

                            b1.WithOwner()
                                .HasForeignKey("ReaderStatusReaderId");
                        });

                    b.Navigation("AntennaList");
                });

            modelBuilder.Entity("Backend.Features.Accesses.Access", b =>
                {
                    b.HasOne("Backend.Features.Tags.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_accesses_tags_tag_id");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Backend.Features.Transactions.Transaction", b =>
                {
                    b.HasOne("Backend.Features.Accesses.Access", "Access")
                        .WithMany()
                        .HasForeignKey("AccessId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_transactions_accesses_access_id");

                    b.Navigation("Access");
                });

            modelBuilder.Entity("Backend.Features.Vehicles.Vehicle", b =>
                {
                    b.HasOne("Backend.Features.Tags.Tag", "Tag")
                        .WithOne("Vehicle")
                        .HasForeignKey("Backend.Features.Vehicles.Vehicle", "TagId")
                        .HasConstraintName("fk_vehicles_tags_tag_id");

                    b.HasOne("Backend.Features.Users.User", "User")
                        .WithMany("Vehicles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vehicles_users_user_id");

                    b.Navigation("Tag");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Features.Tags.Tag", b =>
                {
                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Backend.Features.Users.User", b =>
                {
                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
